name: SEO and Performance Audit
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URL with Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://debatre.com/
          # Menggunakan file lighthouserc.json yang baru
          configPath: ./lighthouserc.json
          runs: 1
        env:
          LHCI_NO_ARTIFACTS: true
